apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    app: my-nginx
    rel: stable
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
        readOnly: true
  
  - name: html-updater
    image: alpine
    command: ["/bin/sh", "-c"]
    args: 
      - while true; do date >> html/index.html; sleep 10; done
    resources:
    volumeMounts:
      - name: html
        mountPath: /html
  volumes:
  - name: html
    emptyDir: {} # Lifecycle tied to pod
